spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
<<<<<<< HEAD
  application:
    name: product-service

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
=======

server:
  port: 19093
>>>>>>> a6ea2fd (feat: 멀티 모듈 구성)
