spring:
  application:
    name: eureka-server

server:
  port: 19090
eureka:
  client:
    register-with-eureka: false
    service-url:
<<<<<<< HEAD
      defaultZone: 'http://localhost:19090/eureka/'
    fetch-registry: false
=======
      defaultZone: http://localhost:19090/eureka
>>>>>>> 2ddeedc (feat: eureka 서버 구성)
  instance:
    hostname: localhost
