spring:
  application:
    name: Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: Order
          uri: lb://Order
          predicates:
            - Path=/order/**
        - id: Product
          uri: lb://Product
          predicates:
            - Path=/products/**
        - id: Auth
          uri: lb://Auth
          predicates:
            - Path=/auth/signIn
      discovery:
        locator:
          enabled: true

server:
  port: 19091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
